export const IS_DEV = process.env.NODE_ENV !== "production";

export const env = {
  APPNAME: process.env.REACT_APP_APPNAME,
  APIADDR: process.env.REACT_APP_APIADDR,
  DEVAPIADDR: process.env.REACT_APP_DEVAPIADDR,
  BASE_URL: process.env.REACT_APP_BASE_URL,
  IPFS_API_URL: process.env.REACT_APP_IPFS_API_URL,
  LOCALNODE: process.env.REACT_APP_LOCALNODE,
  NETWORK: process.env.REACT_APP_NETWORK,
  PRIVATENODE: process.env.REACT_APP_PRIVATENODE,
  GOVERNANCE_CONTRACT_ADDRESS:
    process.env.REACT_APP_GOVERNANCE_CONTRACT_ADDRESS,
  GOVERNANCE_TOKEN_CONTRACT_ADDRESS:
    process.env.REACT_APP_GOVERNANCE_TOKEN_CONTRACT_ADDRESS,
  GOVERNANCE_TOKEN_NAME: process.env.REACT_APP_GOVERNANCE_TOKEN_NAME,
  ACCRUING_TOKEN_NAME: process.env.REACT_APP_ACCRUING_TOKEN_NAME,
  MINIMUM_VOTING_PERIOD: process.env.REACT_APP_MINIMUM_VOTING_PERIOD,
  MAXIMUM_VOTING_PERIOD: process.env.REACT_APP_MAXIMUM_VOTING_PERIOD,
  MINIMUM_VOTING_PERIOD_UNIT: process.env.REACT_APP_MINIMUM_VOTING_PERIOD_UNIT,
  GOVERNANCE_TOKEN_LOGO_ADDRESS:
    process.env.REACT_APP_GOVERNANCE_TOKEN_LOGO_ADDRESS,
};
